name: qr_code_generator
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  gap: ^2.0.1
  google_fonts: ^4.0.1
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  path_provider: ^2.0.12
  share_plus: ^6.3.1
  screenshot: ^1.3.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: poppins_bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: poppins_regular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: poppins_semi_bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    - family: poppins_extra_bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
